name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Build javadoc
        run: |
          mvn install -DskipTests -Dgpg.skip
          mvn javadoc:aggregate

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/apidocs
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
